baseURL = "https://fkowalewski.duckdns.org"
title = "Filip Kowalewski"

DefaultContentLanguage = 'en'

[languages]
  [languages.en]
    languageName = 'English'
    weight = 1

  [[languages.en.menu.main]]
    name = "projects"
    url = "/projects"
    weight = 10

  [[languages.en.menu.main]]
    name = "about"
    url = "/about"
    weight = 20

  [[languages.en.menu.main]]
    name = "contact"
    url = "/contact"
    weight = 30

  [languages.pl]
    languageName = 'Polish'
    weight = 2

  [[languages.pl.menu.main]]
    name = "projekty"
    url = "/pl/projects"
    weight = 10

  [[languages.pl.menu.main]]
    name = "o mnie"
    url = "/pl/about"
    weight = 20

  [[languages.pl.menu.main]]
    name = "kontakt"
    url = "/pl/contact"
    weight = 30
